# Introduction {#Intro}

This book has five chapters. The first two chapters introduce us to bonds. Chapter 1 introduces present value, the most important concept in finance. You *must* understand present value to be able to price bonds. Luckily, the math is very simple and I'll link to online calculators online that make it even easier to do. Chapter 2 is on pricing bonds, which is just finding the present value of the bond. I'll also introduce some terms and ideas in this chapter that I'll use for the rest of the book. 

The next two chapters dive deeper into bonds. Chapter 3 takes up convexity, which will smell mathematical but is actually a very simple idea that is obscured by math. Convexity is extremely desirable, and bonds naturally have convexity. It's one of the reasons I believe they are an essential component of a well-constructed investment portfolio. The Chapter 4 looks at duration, which will be our main tool to determine how risky a bond is. The idea is that by controlling our exposure to duration, we can control how risky our bond position is. 

In the last two chapters, we're going to talk about portfolio construction. Chapter 5 takes a deep dive into the the yield curve. You might have heard it in the news - an "inverted yield curve" can indicate an oncoming recession. But the yield curve contains so much more information than just being an occasional recession indicator, and being able to "read" the information in the yield curve will help you construct an investment portfolio that's more suited to your needs. Chapter 6 presents two ficticious people, and their financial goals. We'll use what we've learned in the previous chapters to construct stock/bond portfolios, and compare how well these portfolios meet their goals to a typical portfolio that an investment advisor at a bank may put them in. 

